package com.pranavs.custompagetransformers

enum class PageTransformStyles {


    SIMPLE_TRANSFORMATION,

    ZOOM_OUT_TRANSFORMATION_FADE_BOTH,
    ZOOM_OUT_TRANSFORMATION_FADE_RIGHT,
    ZOOM_OUT_TRANSFORMATION_FADE_LEFT,
    ZOOM_OUT_LEFT_TRANSFORMATION_FADE_LEFT,
    ZOOM_OUT_RIGHT_TRANSFORMATION_FADE_RIGHT,
    ZOOM_OUT_LEFT_TRANSFORMATION_FADE_RIGHT,
    ZOOM_OUT_RIGHT_TRANSFORMATION_FADE_LEFT,

    CLOCK_SPIN_TRANSFORMATION,
    CLOCK_SPIN_TRANSFORMATION_FADE_BOTH,
    CLOCK_SPIN_TRANSFORMATION__FADE_START,
    CLOCK_SPIN_TRANSFORMATION_FADE_END,
    CLOCK_SPIN_TRANSFORMATION_FLY,
    CLOCK_SPIN_TRANSFORMATION_FLY_FADE_START,
    CLOCK_SPIN_TRANSFORMATION_FLY_FADE_END,
    CLOCK_SPIN_TRANSFORMATION_FLY_FADE_BOTH,

    ANTI_CLOCK_SPIN_TRANSFORMATION,
    ANTI_CLOCK_SPIN_TRANSFORMATION_FADE_BOTH,
    ANTI_CLOCK_SPIN_TRANSFORMATION_FADE_START,
    ANTI_CLOCK_SPIN_TRANSFORMATION_FADE_END,
    ANTI_CLOCK_SPIN_TRANSFORMATION_FLY,
    ANTI_CLOCK_SPIN_TRANSFORMATION_FLY_FADE_BOTH,
    ANTI_CLOCK_SPIN_TRANSFORMATION_FLY_FADE_START,
    ANTI_CLOCK_SPIN_TRANSFORMATION_FLY_FADE_END,



    //Flip transformation
    HORIZONTAL_FLIP_TRANSFORMATION,
    HORIZONTAL_FLIP_TRANSFORMATION_FADE_BOTH,
    HORIZONTAL_FLIP_TRANSFORMATION_FADE_START,
    HORIZONTAL_FLIP_TRANSFORMATION_FADE_END,

    VERTICAL_FLIP_TRANSFORMATION,
    VERTICAL_FLIP_TRANSFORMATION_FADE_BOTH,
    VERTICAL_FLIP_TRANSFORMATION_FADE_START,
    VERTICAL_FLIP_TRANSFORMATION_FADE_END,

    /**
     * Depth transformations
     */


    DEPTH_TRANSFORMATION,
    DEPTH_TRANSFORMATION_FADE_BOTH,
    DEPTH_TRANSFORMATION_FADE_START,
    DEPTH_TRANSFORMATION_FADE_END,
    DEPTH_TRANSFORMATION_SCALE_BOTH,
    DEPTH_TRANSFORMATION_SCALE_BOTH_FADE_START,
    DEPTH_TRANSFORMATION_SCALE_BOTH_FADE_END,
    DEPTH_TRANSFORMATION_SCALE_END,

    /**
     * Pop transformation
     */

    POP_TRANSFORMATION,
    POP_TRANSFORMATION_FADE_BOTH,
    POP_TRANSFORMATION_FADE_START,
    POP_TRANSFORMATION_FADE_END,
    POP_TRANSFORMATION_SCALE_START,
    POP_TRANSFORMATION_SCALE_END,
    POP_TRANSFORMATION_SCALE_BOTH,
    POP_TRANSFORMATION_SCALE_BOTH_FADE_START,
    POP_TRANSFORMATION_SCALE_BOTH_FADE_END,

    FADE_OUT_TRANSFORMATION,


    /**
     * CUBE_OUT out transformation
     */
    CUBE_OUT_TRANSFORMATION,
    CUBE_OUT_TRANSFORMATION_FADE_BOTH,
    CUBE_OUT_TRANSFORMATION_FADE_START,
    CUBE_OUT_TRANSFORMATION_FADE_END,
    CUBE_OUT_TRANSFORMATION_SCALE_START,
    CUBE_OUT_TRANSFORMATION_SCALE_END,
    CUBE_OUT_TRANSFORMATION_SCALE_BOTH,
    CUBE_OUT_TRANSFORMATION_SCALE_BOTH_FADE_START,
    CUBE_OUT_TRANSFORMATION_SCALE_BOTH_FADE_END,




    /**
     * Vertical shut transformation
     */
    VERTICAL_SHUT_TRANSFORMATION,
    VERTICAL_SHUT_TRANSFORMATION_FADE_BOTH,
    VERTICAL_SHUT_TRANSFORMATION_FADE_START,
    VERTICAL_SHUT_TRANSFORMATION_FADE_END,
    VERTICAL_SHUT_TRANSFORMATION_SCALE_START,
    VERTICAL_SHUT_TRANSFORMATION_SCALE_END,
    VERTICAL_SHUT_TRANSFORMATION_SCALE_BOTH,
    VERTICAL_SHUT_TRANSFORMATION_SCALE_BOTH_FADE_BOTH,
    VERTICAL_SHUT_TRANSFORMATION_SCALE_BOTH_FADE_START,
    VERTICAL_SHUT_TRANSFORMATION_SCALE_BOTH_FADE_END,


    /**
     * Horizonatl shut transformation
     */
    HORIZONTAL_SHUT_TRANSFORMATION,
    HORIZONTAL_SHUT_TRANSFORMATION_FADE_BOTH,
    HORIZONTAL_SHUT_TRANSFORMATION_FADE_START,
    HORIZONTAL_SHUT_TRANSFORMATION_FADE_END,
    HORIZONTAL_SHUT_TRANSFORMATION_SCALE_START,
    HORIZONTAL_SHUT_TRANSFORMATION_SCALE_END,
    HORIZONTAL_SHUT_TRANSFORMATION_SCALE_BOTH,
    HORIZONTAL_SHUT_TRANSFORMATION_SCALE_BOTH_FADE_START,
    HORIZONTAL_SHUT_TRANSFORMATION_SCALE_BOTH_FADE_END,
    HORIZONTAL_SHUT_TRANSFORMATION_SCALE_BOTH_FADE_BOTH,



    /**
     *Tinder transformation
     */
    TINDER_TOP_LEFT_TRANSFORMATION,
    TINDER_TOP_LEFT_TRANSFORMATION_FADE_BOTH,
    TINDER_TOP_LEFT_TRANSFORMATION_FADE_START,
    TINDER_TOP_LEFT_TRANSFORMATION_FADE_END,
    TINDER_TOP_LEFT_TRANSFORMATION_SCALE_START,
    TINDER_TOP_LEFT_TRANSFORMATION_SCALE_END,
    TINDER_TOP_LEFT_TRANSFORMATION_SCALE_BOTH,
    TINDER_TOP_LEFT_TRANSFORMATION_SCALE_BOTH_FADE_START,
    TINDER_TOP_LEFT_TRANSFORMATION_SCALE_BOTH_FADE_END,
    TINDER_TOP_LEFT_TRANSFORMATION_SCALE_BOTH_FADE_BOTH,

    TINDER_BOTTOM_LEFT_TRANSFORMATION,
    TINDER_BOTTOM_LEFT_TRANSFORMATION_FADE_BOTH,
    TINDER_BOTTOM_LEFT_TRANSFORMATION_FADE_START,
    TINDER_BOTTOM_LEFT_TRANSFORMATION_FADE_END,
    TINDER_BOTTOM_LEFT_TRANSFORMATION_SCALE_START,
    TINDER_BOTTOM_LEFT_TRANSFORMATION_SCALE_END,
    TINDER_BOTTOM_LEFT_TRANSFORMATION_SCALE_BOTH,
    TINDER_BOTTOM_LEFT_TRANSFORMATION_SCALE_BOTH_FADE_START,
    TINDER_BOTTOM_LEFT_TRANSFORMATION_SCALE_BOTH_FADE_END,
    TINDER_BOTTOM_LEFT_TRANSFORMATION_SCALE_BOTH_FADE_BOTH,


    TINDER_BOTTOM_RIGHT_TRANSFORMATION,
    TINDER_BOTTOM_RIGHT_TRANSFORMATION_FADE_BOTH,
    TINDER_BOTTOM_RIGHT_TRANSFORMATION_FADE_START,
    TINDER_BOTTOM_RIGHT_TRANSFORMATION_FADE_END,
    TINDER_BOTTOM_RIGHT_TRANSFORMATION_SCALE_START,
    TINDER_BOTTOM_RIGHT_TRANSFORMATION_SCALE_END,
    TINDER_BOTTOM_RIGHT_TRANSFORMATION_SCALE_BOTH,
    TINDER_BOTTOM_RIGHT_TRANSFORMATION_SCALE_BOTH_FADE_START,
    TINDER_BOTTOM_RIGHT_TRANSFORMATION_SCALE_BOTH_FADE_END,
    TINDER_BOTTOM_RIGHT_TRANSFORMATION_SCALE_BOTH_FADE_BOTH,





    TINDER_TOP_RIGHT_TRANSFORMATION,
    TINDER_TOP_RIGHT_TRANSFORMATION_FADE_BOTH,
    TINDER_TOP_RIGHT_TRANSFORMATION_FADE_START,
    TINDER_TOP_RIGHT_TRANSFORMATION_FADE_END,
    TINDER_TOP_RIGHT_TRANSFORMATION_SCALE_START,
    TINDER_TOP_RIGHT_TRANSFORMATION_SCALE_END,
    TINDER_TOP_RIGHT_TRANSFORMATION_SCALE_BOTH,
    TINDER_TOP_RIGHT_TRANSFORMATION_SCALE_BOTH_FADE_START,
    TINDER_TOP_RIGHT_TRANSFORMATION_SCALE_BOTH_FADE_END,
    TINDER_TOP_RIGHT_TRANSFORMATION_SCALE_BOTH_FADE_BOTH,




    GATE_TRANSFORMATION,



}